name: Publish to Maven Local (Dev)

on:
  push:
    branches: ["publishing-dev"]
    tags: ["*"]

jobs:
  publish-local:
    runs-on: ubuntu-latest

    env:
      MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
      MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}

      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "Detected release tag: ${GITHUB_REF_NAME}"
          else
            echo "version=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
            echo "Non-tag build, using version dev-${GITHUB_SHA::7}"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and publish to local Maven repo
        run: ./gradlew clean publishToMavenLocal -Pversion=${{ env.version }}