name: Assemble and publish to Maven Central

on:
  push:
    tags: ["*"]
    branches:
      - "feature/*"


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_PORTAL_USERNAME }}
      MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PORTAL_PASSWORD }}

      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "Detected release tag: ${GITHUB_REF_NAME}"
          elif [[ "${GITHUB_REF_TYPE}" == "branch" && "${GITHUB_REF_NAME}" =~ ^feature/ ]]; then
            branch="${GITHUB_REF_NAME#feature/}"
            sanitized_branch=$(echo "$branch" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            short_sha=$(echo "${GITHUB_SHA::7}")
            echo "version=0.0.0-${sanitized_branch}-${short_sha}" >> $GITHUB_ENV
            echo "Feature build detected: ${sanitized_branch} (${short_sha})"
          else
            echo "version=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
            echo "Non-tag, non-feature build: dev-${GITHUB_SHA::7}"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and publish
        run: ./gradlew clean publishAllPublicationsToProjectLocalRepository zipMavenCentralPortalPublication releaseMavenCentralPortalPublication -Pversion=${{ env.version }}